#!/bin/bash

# .envrc 以下のディレクトリでのみ使えるエイリアスを
# 定義するためのユーティリティ関数
# .envrc に
#
#   alias t 'npm test --'
#
# のように記述して使用する

alias_dir=$PWD/.direnv/aliases
rm -rf "$alias_dir"

alias() {
  if [ -z "$alias_init" ]; then
    oldpath="$PATH"
    mkdir -p "$alias_dir"
    PATH_add "$alias_dir"
  fi
  alias_init="true"

  name=$1; shift
  target="$alias_dir/$name"
  echo "#!$SHELL" > "$target"
  echo "PATH=\"$oldpath\"" >> "$target"
  echo "$* \"\$@\"" >> "$target"
  chmod +x "$target"
}
