#!/bin/bash

config_home="${XDG_CONFIG_HOME:-~/.config}"
dot_dir="$(ghq root)/github.com/shiradofu/dotfiles/env/wsl"
mode=
d= # dotfiles 内のファイルパス
w= # windows/wsl が実際に参照するファイルパス
password=
prompt='password: '

__wsl_env_path() {
  cmd.exe /c echo "%$1%" 2>/dev/null | tr '\\' '/' | tr -d '\r' | sed -e 's@\(\w\):@/mnt/\L\1@'
}

__wslsync_wezterm() {
  home=$(__wsl_env_path USERPROFILE)
  d="$config_home/wezterm/wezterm.lua"
  w="$home/.config/wezterm/wezterm.lua"
  __wslsync_do
}

__wslsync_wslconfig() {
  home=$(__wsl_env_path USERPROFILE)
  d="$dot_dir/.wslconfig"
  w="$home/.wslconfig"
  __wslsync_do
}

__wslsync_wsl_conf() {
  d="$dot_dir/wsl.conf"
  w="/etc/wsl.conf"
  __wslsync_sudo
}

__wslsync_resolv_conf() {
  d="$dot_dir/resolv.conf"
  w="/etc/resolv.conf"
  __wslsync_sudo
}

__wslsync_do() {
  mkdir -p "$(dirname "$w")"
  case "$mode" in
    TO_WINDOWS  ) cp -f "$d" "$w";;
    TO_DOTFILES ) cp -f "$w" "$d";;
  esac
}

__wslsync_sudo() {
  if [ -z "$password" ]; then
    echo -n "$prompt"
    read -r -s password
    echo
  fi
  echo "$password" | sudo -S mkdir -p "$(dirname "$w")"
  case "$mode" in
    TO_WINDOWS  ) echo "$password" | sudo -S cp -f "$d" "$w";;
    TO_DOTFILES ) echo "$password" | sudo -S cp -f "$w" "$d";;
  esac
}

for ARG; do
  case $ARG in
    --to-windows  ) mode=TO_WINDOWS;;
    --to-dotfiles ) mode=TO_DOTFILES;;
    -S ) prompt='';;
    wezterm | wslconfig | wsl_conf | resolv_conf )
      "__wslsync_${ARG}"
      ;;
    * )
      echo "invalid argument: $ARG"
      exit 1
      ;;
  esac
done
