tap "espanso/espanso"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "mas"
brew "colima"
cask "amorphousdiskmark"
cask "alt-tab"
cask "anki"
cask "bitwarden"
cask "cyberduck"
cask "dropbox"
cask "espanso"
cask "figma"
cask "google-chrome"
cask "kap"
cask "karabiner-elements"
cask "keycastr"
cask "kindle"
cask "ngrok"
cask "obsidian"
cask "raycast"
cask "slack"
cask "topnotch"
cask "wezterm"
cask "zoom"
mas "Bitwarden", id: 1352778147
mas "Kindle", id: 302584613
mas "LadioCast", id: 411213048
mas "LINE", id: 539883307
mas "Spark", id: 1176895641
mas "AdGuard for Safari", id: 1440147259
mas "Dark Reader for Safari", id: 1438243180
mas "Keepa - Price Tracker", id: 1533805339
mas "Vimari", id: 1480933944
