[[plugins]]
repo = 'mattn/vim-findroot'
hook_add = '''
let g:findroot_patterns = ['.git/']
let g:findroot_not_for_subdir = 0
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'call plug#lightline#hook_add()'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add = 'call plug#coc#hook_add()'

[[plugins]]
repo = 'antoinemadec/coc-fzf'
depends = 'coc.nvim'

[[plugins]]
repo = 'liuchengxu/vista.vim'
hook_add = 'call plug#vista#hook_add()'
