[[plugins]]
repo = '907th/vim-auto-save'
on_event = 'VimEnter'
hook_add = 'call plug#auto_save#hook_add()'

[[plugins]]
repo = 'tpope/vim-repeat'
on_func = 'repeat#set'
hook_post_source = 'call plug#repeat#hook_post_source()'

[[plugins]]
repo = 'nicwest/vim-camelsnek'
on_cmd = ['CamelB', 'Camel', 'Snek', 'Kebab']

[[plugins]]
repo = 'Yggdroot/indentLine'
on_event = 'BufEnter'
hook_source = '''
let g:indentLine_char = '│'
let g:indentLine_fileTypeExclude = ['help', 'vista', 'fern']
'''

[[plugins]]
repo = 'LunarWatcher/auto-pairs'
on_event = 'VimEnter'
hook_post_source = 'call plug#autopairs#hook_post_source()'

[[plugins]]
repo ='junegunn/goyo.vim'
on_cmd = 'Goyo'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
build = 'sh -c "cd app && yarn install"'
on_map = '<Plug>MarkdownPreviewToggle'

[[plugins]]
repo = 'RRethy/vim-hexokinase'
build = 'make hexokinase' # golang required
on_event = 'VimEnter'
hook_source = '''
let g:Hexokinase_ftOptInPatterns = {
      \ 'vim': 'full_hex',
      \ 'yaml': 'full_hex',
      \}
'''
hook_post_source = 'HexokinaseTurnOn'

