[[plugins]]
repo = 'airblade/vim-gitgutter'
on_event = 'VimEnter'
hook_add = 'call plug#gitgutter#hook_add()'

[[plugins]]
repo = 'tpope/vim-fugitive'
depends = 'vim-rhubarb'
on_cmd = ['Git', 'Gdiffsplit', 'GBrowse']
hook_add = 'call plug#fugitive#hook_add()'
hook_post_source = 'call plug#fugitive#hook_post_source()'

[[plugins]]
repo = 'tpope/vim-rhubarb'
on_cmd = 'GBrowse'

[[plugins]]
repo = 'tpope/vim-dispatch'
on_cmd = 'Dispatch'
