[[plugins]]
repo = 'haya14busa/is.vim'
on_event = 'VimEnter'

[[plugins]]
repo = 'haya14busa/vim-asterisk'
depends = ['is.vim']
on_map = ['<Plug>(asterisk-']
hook_post_source  = 'let g:asterisk#keeppos = 1'

[[plugins]]
repo = 'jesseleite/vim-agriculture'
on_cmd = ['RgIgnore', 'RgNoIgnore']
on_func = ['RgVisual', 'RgCword']

[[plugins]]
repo = 'thinca/vim-qfreplace'
on_cmd = 'Qfreplace'
