#!/bin/bash

# .envrc 以下のディレクトリでのみ使えるエイリアス
# .envrc に
#
#   alias t 'npm test --'
#
# のように記述して使用する

alias_dir=$PWD/.direnv/aliases
rm -rf "$alias_dir"

alias() {
  name=$1; shift
  target="$alias_dir/$name"
  mkdir -p "$alias_dir"
  PATH_add "$alias_dir"
  echo "#!$SHELL" > "$target"
  echo "$* \"\$@\"" >> "$target"
  chmod +x "$target"
}
