[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_cmd = ['help', 'h']
hook_source = 'set helplang=ja,en'

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
  nmap go <Plug>(caw:hatpos:toggle)
  xmap go <Plug>(caw:hatpos:toggle)
  nmap gO <Plug>(caw:box:comment)
  xmap gO <Plug>(caw:box:comment)
  autocmd FileType toml let b:caw_oneline_comment = '#'
'''
on_map = ['<Plug>(caw:']

[[plugins]]
repo = 'terryma/vim-multiple-cursors'
on_map = ['<C-n>', 'g<C-n>', '<C-x>', '<C-p>']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = ['<Plug>(openbrowser-smart-search)']
hook_add = '''
  let g:netrw_nogx = 1 " disable netrw's gx mapping.
  nmap gx <Plug>(openbrowser-smart-search)
  vmap gx <Plug>(openbrowser-smart-search)
'''
