-- require("neogit").setup {
--   disable_signs = false,
--   disable_hint = false,
--   disable_context_highlighting = false,
--   disable_commit_confirmation = false,
--   auto_refresh = true,
--   disable_builtin_notifications = false,
--   use_magit_keybindings = false,
--   commit_popup = {
--     kind = "split",
--   },
--   -- Change the default way of opening neogit
--   kind = "tab",
--   -- customize displayed signs
--   signs = {
--     -- { CLOSED, OPENED }
--     section = { ">", "v" },
--     item = { ">", "v" },
--     hunk = { "", "" },
--   },
--   integrations = { diffview = true },
-- }
