  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
      target: dev
    volumes:
      - .:/var/www/app
    command: >
      sh -c
      'if [ ! -d ./vendor ]; then composer install; fi &&
      ./docker/app/wait-for-it.sh db:3306 -t 30 &&
      find storage/ ! -name ".gitignore" | xargs chmod 777 &&
      chown -R www-data:www-data ./storage/logs ./storage/framework &&
      php artisan optimize:clear &&
      php artisan migrate --force &&
      php artisan db:seed &&
      php-fpm'
