#!/bin/bash

config_home="${XDG_CONFIG_HOME:-~/.config}"
windows_home=$(cd "$(dirname "$0")";pwd)
mode=
d= # dotfiles 内のファイルパス
u= # 実際に使われている設定ファイルのファイルパス
password=
prompt='password: '

__wslsync_wezterm() {
  # wezterm must be installed by winget with `--location %APPDATA%/WezTerm`
  if ! appdata=$(wslpath "$(wslvar APPDATA)"); then
    echo 'Failed to get APPDATA'
    exit 1
  fi
  d="$config_home/wezterm/wezterm.lua"
  u="$appdata/WezTerm/wezterm.lua"
  __wslsync_do
}

__wslsync_wslconfig() {
  userprofile=$(wslpath "$(wslvar USERPROFILE)")
  d="$windows_home/.wslconfig"
  u="$userprofile/.wslconfig"
  __wslsync_do
}

__wslsync_wsl_conf() {
  d="$windows_home/wsl.conf"
  u="/etc/wsl.conf"
  __wslsync_sudo
}

__wslsync_do() {
  mkdir -p "$(dirname "$u")"
  case "$mode" in
    LINK ) ln -s "$d" "$u";;
    APPLY ) cp -f "$d" "$u";;
    IMPORT ) cp -f "$u" "$d";;
    BACKUP ) cp -f "$u" "$d.bak";;
    RESTORE ) cp -f "$d.bak" "$u";;
  esac
}

__wslsync_sudo() {
  if [ -z "$password" ]; then
    echo -n "$prompt"
    read -r -s password
    echo
  fi
  echo "$password" | sudo -S mkdir -p "$(dirname "$u")"
  case "$mode" in
    LINK ) echo "$password" | sudo -S ln -s "$d" "$u";;
    APPLY ) echo "$password" | sudo -S cp -f "$d" "$u";;
    IMPORT ) echo "$password" | sudo -S cp -f "$u" "$d";;
    BACKUP ) echo "$password" | sudo -S cp -f "$u" "$d.bak";;
    RESTORE ) echo "$password" | sudo -S cp -f "$d.bak" "$u";;
  esac
}

for ARG; do
  case $ARG in
    link ) mode=LINK;;
    apply ) mode=APPLY;;
    import ) mode=IMPORT;;
    backup ) mode=BACKUP;;
    restore ) mode=RESTORE;;
    -S ) prompt='';;
    alt-tab | espanso | rectangle | wezterm | wslconfig | wsl_conf )
      "__wslsync_${ARG}"
      ;;
    * )
      echo "invalid argument: $ARG"
      exit 1
      ;;
  esac
done
