[[plugins]]
repo = 'mattn/vim-sonictemplate'
on_event = 'VimEnter'
hook_add = '''
let g:sonictemplate_vim_template_dir = g:config_dir . '/templates'
nmap <plug>(sonictemplate-no-mapping1) <plug>(sonictemplate)
nmap <plug>(sonictemplate-no-mapping2) <plug>(sonictemplate-intelligent)
let g:sonictemplate_key = 0
let g:sonictemplate_intelligent_key = 0
let g:sonictemplate_postfix_key = 0
'''
