# ruby
[[plugins]]
repo = 'tpope/vim-endwise'
ft_on = ['ruby']

# JS/TS
[[plugins]]
repo = 'leafgarland/typescript-vim'
ft_on = ['typescript']

# HTML
[[plugins]]
repo = 'mattn/emmet-vim'
ft_on = ['html']

# toml
[[plugins]]
repo = 'cespare/vim-toml'
ft_on = ['toml']

[[plugins]]
repo = 'inkarkat/vim-SyntaxRange'
ft_on = ['toml']

# for multi languages
[[plugins]]
repo = 'tpope/vim-ragtag'
ft_on = [
  'html',
  'xhtml',
  'wml',
  'xml',
  'xslt',
  'xsd',
  'jsp',
  'php',
  'aspperl',
  'aspvbs',
  'cf',
  'mason',
  'htmldjango',
  'eruby'
]

