[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_cmd = ['help', 'h']
hook_source = 'set helplang=ja,en'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'
on_map = ['<C-n>', 'g<C-n>', '<C-x>', '<C-p>']

[[plugins]]
repo = 'junegunn/goyo.vim'
on_cmd = ['Goyo']

[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = '''
  nmap z; <Plug>NERDCommenterToggle
  nmap z/ <Plug>NERDCommenterInvert
  nmap zy <Plug>NERDCommenterYank
  nmap z' <Plug>NERDCommenterAppend<space>
  nmap zB <Plug>NERDCommenterSexy
  xmap z; <Plug>NERDCommenterToggle
  xmap z/ <Plug>NERDCommenterInvert
  xmap zy <Plug>NERDCommenterYank
  xmap zB <Plug>NERDCommenterSexy
'''
on_map = ['<Plug>NERDCommenter']

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
  nmap zn <Plug>(caw:jump:comment-next)<space>
  nmap zp <Plug>(caw:jump:comment-prev)<space>
  nmap z<C-b> <Plug>(caw:box:comment)
  xmap z<C-b> <Plug>(caw:box:comment)
'''
on_map = ['<Plug>(caw:']

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
  let g:netrw_nogx = 1 " disable netrw's gx mapping.
  nmap gx <Plug>(openbrowser-smart-search)
  vmap gx <Plug>(openbrowser-smart-search)
'''
on_map = ['<Plug>(openbrowser-smart-search)']

