[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'call plug#lightline#hook_add()'

##############################################
##############################################
##############################################

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add ='call plug#fern#hook_source()'

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'
